djangexample:
  build: djangoexample
  env_file:
    - databag/common.env
    - databag/celery.env
    - databag/mysql.env
    - databag/develop.env

spoiload:
  build: spoiload

nginx:
  image: nginx:latest
  volumes_from:
    - volume-nginx

rundeck:
  image: jordan/rundeck:latest

elasticsearch:
  image: elasticsearch:latest

mongodb:
  image: mongo:latest

postgresql:
  image: postgres:latest

fluentd:
  image: fluent/fluentd:latest

logstash:
  image: logstash:latest

rabbitmq:
  image: rabbitmq:latest

redis:
  image: busybox:latest

mysql:
  image: mysql:latest
  volumes_from:
    - volume-mysql

fake-s3:
  image: lphoward/fake-s3:latest
  volumes_from:
    - volume-fake-s3

volume-fake-s3:
  image: busybox:latest
  volumes:
    - /var/lib/sximada/fake-s3/fakes3_root:/fakes3_root

volume-nginx:
  image: busybox:latest

volume-mysql:
  image: busybox:latest

volume-app:
  image: busybox:latest

volume-djangoexample:
  image: busybox:latest
    - /var/lib/sximada/djangoexample/srv/sximada/djangoexample/src:/srv/sximada/djangoexample/src
